write-host ">>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
write-host ">+                                                    +<"
write-host ">                                                      <"
write-host ">                                                      <"
write-host ">                        menu                          <"
write-host ">                                                      <"
write-host ">                                                      <"
write-host ">                                                      <"
write-host ">         1. convierte de hexadecimal a binario        <"
write-host ">         2. convierte de binario a octal              <"
write-host ">         3. convierte de binario a hexadecimal        <"
write-host ">                                                      <"
write-host ">                                                      <"
write-host ">                                                      <"
write-host ">+                                                    +<"
write-host ">>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
$var=read-host "selecciona script"